// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package global

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.abandonOrphanSessionsStmt, err = db.PrepareContext(ctx, abandonOrphanSessions); err != nil {
		return nil, fmt.Errorf("error preparing query AbandonOrphanSessions: %w", err)
	}
	if q.completeSessionStmt, err = db.PrepareContext(ctx, completeSession); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteSession: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.listSessionIDsStmt, err = db.PrepareContext(ctx, listSessionIDs); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionIDs: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listSessionsByProjectStmt, err = db.PrepareContext(ctx, listSessionsByProject); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsByProject: %w", err)
	}
	if q.updateWorktreeBranchStmt, err = db.PrepareContext(ctx, updateWorktreeBranch); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWorktreeBranch: %w", err)
	}
	if q.upsertSessionStmt, err = db.PrepareContext(ctx, upsertSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSession: %w", err)
	}
	if q.upsertSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, upsertSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSessionTitleAndUsage: %w", err)
	}
	if q.upsertSessionUsageStmt, err = db.PrepareContext(ctx, upsertSessionUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSessionUsage: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.abandonOrphanSessionsStmt != nil {
		if cerr := q.abandonOrphanSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing abandonOrphanSessionsStmt: %w", cerr)
		}
	}
	if q.completeSessionStmt != nil {
		if cerr := q.completeSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.listSessionIDsStmt != nil {
		if cerr := q.listSessionIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionIDsStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionsByProjectStmt != nil {
		if cerr := q.listSessionsByProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsByProjectStmt: %w", cerr)
		}
	}
	if q.updateWorktreeBranchStmt != nil {
		if cerr := q.updateWorktreeBranchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWorktreeBranchStmt: %w", cerr)
		}
	}
	if q.upsertSessionStmt != nil {
		if cerr := q.upsertSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSessionStmt: %w", cerr)
		}
	}
	if q.upsertSessionTitleAndUsageStmt != nil {
		if cerr := q.upsertSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	if q.upsertSessionUsageStmt != nil {
		if cerr := q.upsertSessionUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSessionUsageStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	abandonOrphanSessionsStmt      *sql.Stmt
	completeSessionStmt            *sql.Stmt
	deleteSessionStmt              *sql.Stmt
	getSessionStmt                 *sql.Stmt
	listSessionIDsStmt             *sql.Stmt
	listSessionsStmt               *sql.Stmt
	listSessionsByProjectStmt      *sql.Stmt
	updateWorktreeBranchStmt       *sql.Stmt
	upsertSessionStmt              *sql.Stmt
	upsertSessionTitleAndUsageStmt *sql.Stmt
	upsertSessionUsageStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		abandonOrphanSessionsStmt:      q.abandonOrphanSessionsStmt,
		completeSessionStmt:            q.completeSessionStmt,
		deleteSessionStmt:              q.deleteSessionStmt,
		getSessionStmt:                 q.getSessionStmt,
		listSessionIDsStmt:             q.listSessionIDsStmt,
		listSessionsStmt:               q.listSessionsStmt,
		listSessionsByProjectStmt:      q.listSessionsByProjectStmt,
		updateWorktreeBranchStmt:       q.updateWorktreeBranchStmt,
		upsertSessionStmt:              q.upsertSessionStmt,
		upsertSessionTitleAndUsageStmt: q.upsertSessionTitleAndUsageStmt,
		upsertSessionUsageStmt:         q.upsertSessionUsageStmt,
	}
}
