// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package global

type Session struct {
	ID               string  `json:"id"`
	Project          string  `json:"project"`
	Title            string  `json:"title"`
	Tokens           int64   `json:"tokens"`
	Cost             float64 `json:"cost"`
	CreatedAt        int64   `json:"created_at"`
	UpdatedAt        int64   `json:"updated_at"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	StationTokens    int64   `json:"station_tokens"`
	Model            string  `json:"model"`
	Provider         string  `json:"provider"`
	Status           string  `json:"status"`
	WorktreeBranch   string  `json:"worktree_branch"`
}
