// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package global

import (
	"context"
)

type Querier interface {
	AbandonOrphanSessions(ctx context.Context, project string) error
	CompleteSession(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	GetSession(ctx context.Context, id string) (Session, error)
	ListSessionIDs(ctx context.Context) ([]string, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSessionsByProject(ctx context.Context, project string) ([]Session, error)
	UpdateWorktreeBranch(ctx context.Context, arg UpdateWorktreeBranchParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
	UpsertSessionTitleAndUsage(ctx context.Context, arg UpsertSessionTitleAndUsageParams) error
	UpsertSessionUsage(ctx context.Context, arg UpsertSessionUsageParams) error
}

var _ Querier = (*Queries)(nil)
