// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package global

import (
	"context"
)

const abandonOrphanSessions = `-- name: AbandonOrphanSessions :exec
UPDATE sessions SET status = 'abandoned' WHERE project = ? AND status = 'active'
`

func (q *Queries) AbandonOrphanSessions(ctx context.Context, project string) error {
	_, err := q.exec(ctx, q.abandonOrphanSessionsStmt, abandonOrphanSessions, project)
	return err
}

const completeSession = `-- name: CompleteSession :exec
UPDATE sessions SET status = 'completed', updated_at = strftime('%s', 'now') WHERE id = ?
`

func (q *Queries) CompleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.completeSessionStmt, completeSession, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, project, title, tokens, cost, created_at, updated_at, prompt_tokens, completion_tokens, station_tokens, model, provider, status, worktree_branch FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Title,
		&i.Tokens,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.StationTokens,
		&i.Model,
		&i.Provider,
		&i.Status,
		&i.WorktreeBranch,
	)
	return i, err
}

const listSessionIDs = `-- name: ListSessionIDs :many
SELECT id FROM sessions
`

func (q *Queries) ListSessionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listSessionIDsStmt, listSessionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, project, title, tokens, cost, created_at, updated_at, prompt_tokens, completion_tokens, station_tokens, model, provider, status, worktree_branch FROM sessions ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Title,
			&i.Tokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.StationTokens,
			&i.Model,
			&i.Provider,
			&i.Status,
			&i.WorktreeBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT id, project, title, tokens, cost, created_at, updated_at, prompt_tokens, completion_tokens, station_tokens, model, provider, status, worktree_branch FROM sessions WHERE project = ? ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByProject(ctx context.Context, project string) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsByProjectStmt, listSessionsByProject, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Title,
			&i.Tokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.StationTokens,
			&i.Model,
			&i.Provider,
			&i.Status,
			&i.WorktreeBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorktreeBranch = `-- name: UpdateWorktreeBranch :exec
UPDATE sessions SET worktree_branch = ? WHERE id = ?
`

type UpdateWorktreeBranchParams struct {
	WorktreeBranch string `json:"worktree_branch"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateWorktreeBranch(ctx context.Context, arg UpdateWorktreeBranchParams) error {
	_, err := q.exec(ctx, q.updateWorktreeBranchStmt, updateWorktreeBranch, arg.WorktreeBranch, arg.ID)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, project, title, tokens, cost, prompt_tokens, completion_tokens, station_tokens, model, provider, status, worktree_branch, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'))
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    tokens = excluded.tokens,
    cost = excluded.cost,
    prompt_tokens = excluded.prompt_tokens,
    completion_tokens = excluded.completion_tokens,
    station_tokens = excluded.station_tokens,
    model = excluded.model,
    provider = excluded.provider,
    status = excluded.status,
    worktree_branch = excluded.worktree_branch,
    updated_at = strftime('%s', 'now')
`

type UpsertSessionParams struct {
	ID               string  `json:"id"`
	Project          string  `json:"project"`
	Title            string  `json:"title"`
	Tokens           int64   `json:"tokens"`
	Cost             float64 `json:"cost"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	StationTokens    int64   `json:"station_tokens"`
	Model            string  `json:"model"`
	Provider         string  `json:"provider"`
	Status           string  `json:"status"`
	WorktreeBranch   string  `json:"worktree_branch"`
	CreatedAt        int64   `json:"created_at"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.exec(ctx, q.upsertSessionStmt, upsertSession,
		arg.ID,
		arg.Project,
		arg.Title,
		arg.Tokens,
		arg.Cost,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.StationTokens,
		arg.Model,
		arg.Provider,
		arg.Status,
		arg.WorktreeBranch,
		arg.CreatedAt,
	)
	return err
}

const upsertSessionTitleAndUsage = `-- name: UpsertSessionTitleAndUsage :exec
INSERT INTO sessions (id, project, title, tokens, cost, prompt_tokens, completion_tokens, station_tokens, model, provider, status, worktree_branch, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?, 0, '', '', 'active', '', strftime('%s', 'now'), strftime('%s', 'now'))
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    prompt_tokens = sessions.prompt_tokens + excluded.prompt_tokens,
    completion_tokens = sessions.completion_tokens + excluded.completion_tokens,
    cost = sessions.cost + excluded.cost,
    updated_at = strftime('%s', 'now')
`

type UpsertSessionTitleAndUsageParams struct {
	ID               string  `json:"id"`
	Project          string  `json:"project"`
	Title            string  `json:"title"`
	Cost             float64 `json:"cost"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
}

func (q *Queries) UpsertSessionTitleAndUsage(ctx context.Context, arg UpsertSessionTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.upsertSessionTitleAndUsageStmt, upsertSessionTitleAndUsage,
		arg.ID,
		arg.Project,
		arg.Title,
		arg.Cost,
		arg.PromptTokens,
		arg.CompletionTokens,
	)
	return err
}

const upsertSessionUsage = `-- name: UpsertSessionUsage :exec
INSERT INTO sessions (id, project, title, tokens, cost, prompt_tokens, completion_tokens, station_tokens, model, provider, status, worktree_branch, created_at, updated_at)
VALUES (?, ?, '', ?, ?, ?, ?, ?, '', '', 'active', '', strftime('%s', 'now'), strftime('%s', 'now'))
ON CONFLICT(id) DO UPDATE SET
    tokens = sessions.tokens + excluded.tokens,
    cost = sessions.cost + excluded.cost,
    prompt_tokens = excluded.prompt_tokens,
    completion_tokens = excluded.completion_tokens,
    station_tokens = sessions.station_tokens + excluded.station_tokens,
    updated_at = strftime('%s', 'now')
`

type UpsertSessionUsageParams struct {
	ID               string  `json:"id"`
	Project          string  `json:"project"`
	Tokens           int64   `json:"tokens"`
	Cost             float64 `json:"cost"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	StationTokens    int64   `json:"station_tokens"`
}

func (q *Queries) UpsertSessionUsage(ctx context.Context, arg UpsertSessionUsageParams) error {
	_, err := q.exec(ctx, q.upsertSessionUsageStmt, upsertSessionUsage,
		arg.ID,
		arg.Project,
		arg.Tokens,
		arg.Cost,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.StationTokens,
	)
	return err
}
