// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    title,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, title, prompt_tokens, completion_tokens, cost, updated_at, created_at, todos, total_tokens, station_tokens
`

type CreateSessionParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession, arg.ID, arg.Title)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Todos,
		&i.TotalTokens,
		&i.StationTokens,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, title, prompt_tokens, completion_tokens, cost, updated_at, created_at, todos, total_tokens, station_tokens
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Todos,
		&i.TotalTokens,
		&i.StationTokens,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, title, prompt_tokens, completion_tokens, cost, updated_at, created_at, todos, total_tokens, station_tokens
FROM sessions
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Todos,
			&i.TotalTokens,
			&i.StationTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    total_tokens = ?,
    station_tokens = ?,
    cost = ?,
    todos = ?
WHERE id = ?
RETURNING id, title, prompt_tokens, completion_tokens, cost, updated_at, created_at, todos, total_tokens, station_tokens
`

type UpdateSessionParams struct {
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	TotalTokens      int64          `json:"total_tokens"`
	StationTokens    int64          `json:"station_tokens"`
	Cost             float64        `json:"cost"`
	Todos            sql.NullString `json:"todos"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.StationTokens,
		arg.Cost,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Todos,
		&i.TotalTokens,
		&i.StationTokens,
	)
	return i, err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :exec
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?
WHERE id = ?
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.updateSessionTitleAndUsageStmt, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}

const updateSessionTodos = `-- name: UpdateSessionTodos :exec
UPDATE sessions
SET
    todos = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionTodosParams struct {
	Todos sql.NullString `json:"todos"`
	ID    string         `json:"id"`
}

func (q *Queries) UpdateSessionTodos(ctx context.Context, arg UpdateSessionTodosParams) error {
	_, err := q.exec(ctx, q.updateSessionTodosStmt, updateSessionTodos, arg.Todos, arg.ID)
	return err
}

const updateSessionUsage = `-- name: UpdateSessionUsage :exec
UPDATE sessions
SET
    prompt_tokens = ?,
    completion_tokens = ?,
    total_tokens = total_tokens + ?,
    station_tokens = station_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionUsageParams struct {
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	TotalTokens      int64   `json:"total_tokens"`
	StationTokens    int64   `json:"station_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionUsage(ctx context.Context, arg UpdateSessionUsageParams) error {
	_, err := q.exec(ctx, q.updateSessionUsageStmt, updateSessionUsage,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.StationTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}
